services:
- type: web
  name: radiotherapie2025
  env: docker
  plan: starter
  repo: https://github.com/Roums215/ath.git
  region: frankfurt
  envVars:
  - key: APP_ENV
    value: prod
  - key: DATABASE_URL
    fromDatabase:
      name: radiotherapie-db
      property: connectionString
  - key: APP_SECRET
    generateValue: true

databases:
- name: radiotherapie-db
  databaseName: symfony
  user: symfony
  plan: free
